export interface LicenseData{
    UISettings: string;
    PrinterServerIP: string;
    ShowModulerAppview: string;
    LaunchFavourate: string;
    CompanyName: string;
    CompanyServer: string;
    ProductVersion: string;
    Language: string;
    DefaultValues: any;
    VersionSuccess: string;
    VersionFlag: string;
    LicenceSuccess: string,
    LicenceResponse: string,
    LoginId: string,
    Password: string,
    CompanyId: string,
    Message: string,
    Token: string,
    AuthenticationToken: string,
    MgsDfltValues: string,
    MenuId: string,
    GUID: string,
    Active: string,
    Product: string,
    UserExceed: string,
    ErrMessage: string,
    SapUser: string
}